### ISSUE TITLE
输入密码后回车显示

### ISSUE THREAD

**Issue by izuolan** [xingrz/swiftzjs#2]
/usr/local/lib/node_modules/swiftz/node_modules/async/lib/async.js:582
                    tasks[index].apply(null, arguments);
                                 ^
TypeError: Cannot call method 'apply' of undefined
    at fn (/usr/local/lib/node_modules/swiftz/node_modules/async/lib/async.js:582:34)
    at Object._onImmediate (/usr/local/lib/node_modules/swiftz/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback](timers.js:354:15)
请问怎么解决？？谢谢～～

**Comment by xingrz** [comment]
这个项目还没正式发布，谢谢支持。
